---
openapi: 3.0.2
info:
  title: todo
  version: 1.0.0
  description: Todo List
  contact:
    name: Jamie Land
    url: http://redhat.com
    email: jland@redhat.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
- url: http://localhost:8080/v1
  description: Localhost
paths:
  /todos:
    get:
      tags:
      - todo
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/todo'
      operationId: getTodos
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/todo'
        required: true
      tags:
      - todo
      responses:
        "201":
          description: Successful response.
      operationId: createTodo
    parameters:
    - name: completed
      schema:
        type: boolean
      in: query
  /todos/{todoId}:
    get:
      tags:
      - todo
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/todo'
        "404":
          description: Todo item not found
      operationId: getTodo
    put:
      requestBody:
        description: Updated `todo` information.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/todo'
        required: true
      tags:
      - todo
      responses:
        "202":
          description: Successful response.
        "404":
          description: Todo item not found
      operationId: updateTodo
    delete:
      tags:
      - todo
      responses:
        "204":
          description: Successful response.
        "404":
          description: Todo item not found
      operationId: deleteTodo
    parameters:
    - name: todoId
      schema:
        type: string
      in: path
      required: true
  /users:
   
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
      operationId: getusers
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
        required: true
      responses:
        "201":
          description: Successful response.
      operationId: createuser
  /users/{userId}:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
      operationId: getuser
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
        required: true
      responses:
        "202":
          description: Successful response.
      operationId: updateuser
    delete:
      responses:
        "204":
          description: Successful response.
      operationId: deleteuser
    parameters:
    - name: userId
      schema:
        type: string
      in: path
      required: true
components:
  schemas:
    todo:
      title: Todo
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        date:
          format: date-time
          type: string
        completed:
          description: Is Completed
          type: boolean
        owner:
          $ref: '#/components/schemas/user'
      example:
        name: Todo item
        date: 2018-05-06T18:25:43.511Z
        completed: true
    user:
      title: Root Type for user
      description: ""
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
      example:
        firstName: Jon
        lastName: Snow
tags:
- name: todo
  description: 'Todo '
